name: coba_shelf
description: A web server built using the shelf package.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  crypto: ^3.0.1
  equatable: ^2.0.3
  jaguar_jwt: ^3.0.0
  shelf: ^1.1.0
  shelf_router: ^1.1.1
  sqlite3: ^1.1.2

dev_dependencies:
  mockito: ^5.0.14
  pedantic: ^1.10.0
  test: ^1.17.11
